/**
 * Nitro plugin — injects the per-request CSP nonce into every <script> tag
 * in the rendered HTML so inline scripts pass the nonce-based CSP policy.
 *
 * The nonce is generated by the security-headers middleware and stored in
 * `event.context.cspNonce`. In dev mode (no nonce), this plugin is a no-op.
 */
export default defineNitroPlugin((nitroApp) => {
  nitroApp.hooks.hook('render:html', (html, { event }) => {
    const nonce: string | undefined = event.context.cspNonce
    if (!nonce) return

    const inject = (parts: string[]) =>
      parts.map((s) => s.replace(/<script(?=[\s>])/gi, `<script nonce="${nonce}"`))

    html.head = inject(html.head)
    html.bodyAppend = inject(html.bodyAppend)
    html.bodyPrepend = inject(html.bodyPrepend)
  })
})
